### ISSUE TITLE
How to compile coq files?

### ISSUE THREAD

**Issue by mikkelmilo** [tchajed/coq-array#2]
In an empty repo, I do as the README says and add the two submodules. This leaves me with the folder structure
```
vendor/
  array/
    src/
    vendor/
       classes/
  simple-classes/
    src/
```
What now? I tried to run `make` in `/vendor/array` but then I get 
```
cat: vendor/classes/libname: No such file or directory
Do you need to run git submodule --init --recursive?
make: *** Deleting file '_CoqProject'
make: *** No rule to make target '_CoqProject', needed by 'src/MultiAssign.vo'.  Stop.
```
and when I run `make` in `/vendor/simple-classes` I get an error
```
COQC src/Ordering.v
File "./src/Ordering.v", line 74, characters 0-47:
Error: This command does not support this attribute: export.
[unsupported-attributes,parsing]

Makefile:34: recipe for target 'src/Ordering.vo' failed
make: *** [src/Ordering.vo] Error 1
```
I'm on coq 8.12.0.

As a starter, I just want to be able to compile the `.vo` files, but later I want to import the `Array` library. How should my folder structure look like in order to do this?

**Comment by spitters** [comment]
Likely related to
https://github.com/coq/coq/issues/13833

**Comment by spitters** [comment]
@tchajed What's the status of this project? Would it be somewhat responsible for us to use it as a dependency?

**Comment by tchajed** [comment]
I no longer use this, and I was never really happy with maintaining a library of typeclasses. Can you use std++ instead? If there's something missing from std++ which is in this library I can help add it.

**Comment by spitters** [comment]
@tchajed Thanks. It would be useful to update the readme to reflect that.

Do you have a specific part of stdpp in mind? They only seem to have arrays in heaplang, which is quite specific.

**Comment by tchajed** [comment]
You can use `take` and `drop` from std++. If you're heavily using subslicing then this library might be more convenient, since it has lemmas that handle both indices simultaneously.

**Comment by mikkelmilo** [comment]
@tchajed We had a brief look at std++'s `vector` before we found coq-array. It was in fact the subslicing functions, combined with default elements, that were appealing in this library :)

**Comment by spitters** [comment]
You mean take and drop here:
https://gitlab.mpi-sws.org/iris/stdpp/-/blob/master/theories/list.v
Which depend on firstn here:
https://coq.inria.fr/library/Coq.Lists.List.html

**Comment by spitters** [comment]
math-comps seq type behaves similarly:
https://github.com/math-comp/math-comp/blob/master/mathcomp/ssreflect/seq.v

**Comment by tchajed** [comment]
Ok I finally fixed everything so it works on Coq 8.10 through master. I thought I was keeping up-to-date but CI was broken (I hadn't migrated away from Travis CI) and locally I only have Coq master, so it turns out coq-array accidentally only support Coq master.

I think you can expect this to keep working with the current features, but it would be a better long-term solution to add subslicing and associated lemmas to std++. I'll ask Robbert about that.

**Comment by tchajed** [comment]
For default elements you can use std++'s `lookup_total`, which has notation `l !!! i`. It uses the `Inhabited` typeclass, which is similar to the use of `Default` here. There's also better support for modification since you have not just `insert` but also `alter` which modifies based on the current value.

**Comment by tchajed** [comment]
I think I addressed everything so I'm closing this issue, please let me know if there's something I missed!
